"""
Django settings for condominio_info project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

import firebase_admin
from decouple import config
from firebase_admin import credentials

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
AUTH_USER_MODEL = 'info.CondominiumProfile'

CSRF_TRUSTED_ORIGINS = ['https://d4wto45otvnl7.cloudfront.net/', 'https://appportaria.com', 'https://www.appportaria.com', 'https://d2ayksyorsu2tj.cloudfront.net/']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'info',
    'crispy_forms',
    'fontawesomefree',
    'django_crontab',
    'pwa',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

CRONJOBS = [
    ('01 00 * * *', 'info.tasks.deactivate_expired_users'),
    ('02 00 * * *', 'info.tasks.notify_expiration'),
    ('03 00 * * *', 'info.tasks.remove_contracts'), ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'condominio_info.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.csrf',
            ],
            'builtins': [
                'info.templatetags.custom_filters',
            ],
        },
    },
]

WSGI_APPLICATION = 'condominio_info.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'media'),
]

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static_cdn')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media_cdn')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# DEFAULT_FROM_EMAIL = "inforesolvido@gmail.com"
DEFAULT_FROM_EMAIL = "contato@appportaria.com.br"
EMAIL_HOST = 'smtp.zoho.eu'
# EMAIL_HOST = 'smtplw.com.br'
EMAIL_PORT = 587
EMAIL_HOST_USER = "contato@appportaria.com.br"
# EMAIL_HOST_USER = "niggl1"
# EMAIL_HOST_PASSWORD = "hugxsvmjrixxihph"
EMAIL_HOST_PASSWORD = "TU4bA8frQmZe"
# EMAIL_HOST_PASSWORD = "IgsBBqMl3726"
EMAIL_USE_TLS = True
EMAIL_ADMIN_NOTIFICATION = "eduardodominikus@hotmail.com"
# EMAIL_ADMIN_NOTIFICATION = "leo.cc14@gmail.com"

DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024

GEOIP_PATH = os.path.join(BASE_DIR, "database/")

PWA_APP_NAME = 'App Portaria'
PWA_APP_DESCRIPTION = "Nosso propósito é registrar em detalhes todo o trabalho realizado no condomínio"
# PWA_APP_THEME_COLOR = '#3A58B7'
# PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
# PWA_APP_SCOPE = '/'
# PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
# PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': 'https://sindicobucket.s3.sa-east-1.amazonaws.com/static/img/PortariaLogo.png',
        'sizes': '512x512'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': 'https://sindicobucket.s3.sa-east-1.amazonaws.com/static/img/PortariaLogo.png',
        'sizes': '512x512'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/img/pwa/Splash.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_LANG = 'pt-BR'
PWA_APP_PERMISSIONS = {
    'geolocation': 'Access your location',
    'notifications': 'Receive notifications',
    'downloads': 'Download files',
}

WABA_TOKEN = "EAAMtnzgB5OcBOZBLWeuOve2QX6JcIapv0y48XYIykwzZCAQZA0IVizZARmHxfN444d2Tg00mMqc7l0wRvIqb6JAyanIPgTfHxk9VNjq3A1nf6ZB6zTk5aeZATqdabFMpNNZB6HsuQYhJPDFb2SWZCdPNXCO4y17XYa4xGjYErRTtaZAsVs0Q827ol7wrPJFHFWGmyeFOeHSKeZCEEZAm4ZAk"
WABA_PHONE_ID = "470967989440609"

WABA_VERIFY_TOKEN = "l30n4rd090"

FIREBASE_CRED = credentials.Certificate(os.path.join(BASE_DIR, 'info', 'config', 'firebase-key.json'))
firebase_admin.initialize_app(FIREBASE_CRED)
