from django.urls import path, re_path

import info.info_viwes.condominium.informative.informative_view
import info.info_viwes.condominium.order.order_view
from . import views
from .info_viwes import condominium_view, administrator_view
from .info_viwes.condominium.apartment import apartment_view
from .info_viwes.condominium.checklist import checklist_view
from .info_viwes.condominium.contract import contract_view
from .info_viwes.condominium.document import document_view
from .info_viwes.condominium.employee import employee_view
from .info_viwes.condominium.firebase import firebase_view
from .info_viwes.condominium.informative import informative_view
from .info_viwes.condominium.intercom import intercom_view
from .info_viwes.condominium.messages import message_view
from .info_viwes.condominium.order import order_view
from .info_viwes.condominium.pedestrian import pedestrian_view
from .info_viwes.condominium.product import product_view
from .info_viwes.condominium.report import report_view
from .info_viwes.condominium.reservation import reservation_view
from .info_viwes.condominium.review import review_view
from .info_viwes.condominium.storage import storage_view
from .info_viwes.condominium.survey import survey_view
from .info_viwes.condominium.timeline import timeline_view
from .info_viwes.condominium.vehicle import vehicle_view

app_name = "info"

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('register/<str:profile>', views.sign_up, name="register"),
    path('sign-up', views.profiles, name="sign-up"),
    path('profile-detail/<str:profile>', views.profile_detail, name="profile-detail"),
    path('sign-in', views.sign_in, name="sign-in"),
    path('sign-out', views.sign_out, name="sign-out"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('dashboard-condominium/<int:id>', administrator_view.dashboard, name="dashboard-condominium"),
    path('forgotten-password', views.reset_password, name="forgotten-password"),
    path('add-apartment', apartment_view.add_apartment, name="add-apartment"),
    path('remove-apartment/<int:id>', apartment_view.delete_apartment, name="delete-apartment"),
    path('remove-block/<int:id>', apartment_view.delete_block, name="delete-block"),
    path('update-block/<int:id>', apartment_view.update_block, name="update-block"),
    path('update-apartment/<int:id>', apartment_view.update_apartment, name="update-apartment"),
    path('add-block', apartment_view.add_block, name="add-block"),
    path('add-resident', apartment_view.add_resident, name="add-resident"),
    path('delete-resident/<int:id>', apartment_view.delete_resident, name="delete-resident"),
    path('get-apartments/', apartment_view.get_apartments, name="get-apartments"),
    path('get-residents/', apartment_view.get_residents, name="get-residents"),
    path('apartments', apartment_view.apartments, name="apartments"),
    path('blocks', apartment_view.blocks, name="blocks"),
    path('residents', apartment_view.residents, name="residents"),
    path('invormative', info.info_viwes.condominium.informative.informative_view.informative, name="informative"),
    path('add-informative', info.info_viwes.condominium.informative.informative_view.add_activity,
         name="add-informative"),
    path('add-informative-kind', informative_view.add_informative_kind,
         name="add-informative-kind"),
    path('edit-informative/<int:id>', info.info_viwes.condominium.informative.informative_view.edit_informative,
         name="edit-informative"),
    path('clone-informative/<int:id>', info.info_viwes.condominium.informative.informative_view.clone_informative,
         name="clone-informative"),
    path('delete-informative/<int:id>', info.info_viwes.condominium.informative.informative_view.delete_informative,
         name="delete-informative"),
    path('delete-all-informative', info.info_viwes.condominium.informative.informative_view.delete_all_informatives,
         name="delete-all-informatives"),
    path('view-informative/<int:id>', info.info_viwes.condominium.informative.informative_view.view_informative,
         name="view-informative"),
    path('export-informative/<int:id>',
         info.info_viwes.condominium.informative.informative_view.export_informative_to_pdf, name="export-informative"),
    path('add-from-excel', views.add_from_file, name="add-from-excel"),
    path('clients', views.clients, name="clients"),
    path('view-profile/<int:id>', views.view_profile, name="view-profile"),
    path('remove-profile/<int:id>', views.remove_profile, name="remove-profile"),
    path('block-profile/<int:id>', views.block_profile, name="block-profile"),
    path('configure-profile/<int:id>', views.configure_profile, name="configure-profile"),
    path('update-email', condominium_view.update_email, name="update-email"),
    path('update-password', condominium_view.update_password, name="update-password"),
    path('update-profile', condominium_view.edit_profile, name="update-profile"),
    path('update-resident-profile', condominium_view.edit_resident_profile, name="update-resident-profile"),
    path('update-resident/<int:id>', info.info_viwes.condominium.apartment.apartment_view.update_resident,
         name="update-resident"),
    path('notify-order', info.info_viwes.condominium.order.order_view.order_notification, name="notify-order"),
    path('update-order/<int:id>', info.info_viwes.condominium.order.order_view.update_order_notification,
         name="update-order"),
    path('view-order/<int:id>', info.info_viwes.condominium.order.order_view.view_order_notification,
         name="view-order"),
    path('orders', info.info_viwes.condominium.order.order_view.orders, name="orders"),
    path("my-orders", info.info_viwes.condominium.order.order_view.my_orders, name="my-orders"),
    path(
        'my-notifications/',
        condominium_view.my_notifications,
        name='my-notifications'
    ),
    path('messages', message_view.messages, name="messages"),
    path("notify", message_view.notify, name="notify"),
    path('message-list', message_view.message_list, name="message-list"),
    path("notification-list", message_view.notification_list, name="notification-list"),
    path('view-message/<int:id>', message_view.view_message, name="view-message"),
    path("view-notification/<int:id>", message_view.view_notification, name="view-notification"),
    path('message-resident', message_view.message_resident, name="message-resident"),
    path("notify-resident", message_view.notify_resident, name="notify-resident"),
    path('message-block', message_view.message_block, name="message-block"),
    path("notify-block", message_view.notify_block, name="notify-block"),
    path('message-all', message_view.message_all, name="message-all"),
    path("notify-all", message_view.notify_all, name="notify-all"),
    path('review', review_view.add_review, name="add-review"),
    path('remove-review/<int:id>', review_view.delete_review, name="delete-review"),
    path('reviews', review_view.reviews, name="reviews"),
    path('review-answers/<int:id>', review_view.answers, name="review-answers"),
    path('answer-detail/<int:id>', review_view.view_answer, name="answer-detail"),
    path('survey-answer-detail/<int:id>', survey_view.view_answer, name="survey-answer-detail"),
    path('add-survey/', survey_view.add_survey, name="add-survey"),
    path('remove-survey/<int:id>', survey_view.delete_survey, name="delete-survey"),
    path('surveys/', survey_view.surveys, name="surveys"),
    path('survey-detail/<int:id>', survey_view.survey_detail, name="survey-detail"),
    path('survey-result/<int:id>', survey_view.survey_result, name="survey-result"),
    path('survey-end/<int:id>', survey_view.end_survey, name="survey-end"),
    path('survey-user-answer/<int:id>', survey_view.add_user_survey_answer, name="survey-user-answer"),
    path('survey-anonimous-answer/<int:id>', survey_view.survey_link, name="survey-anonimous-answer"),
    path('survey-votes-report/<int:survey_id>', report_view.survey_votes_report, name="survey-votes-report"),
    path('add-contract/', contract_view.add_contract_expiration, name="add-contract"),
    path('view-contract/<int:id>', info.info_viwes.condominium.contract.contract_view.view_contract,
         name="view-contract"),
    path('edit-contract/<int:id>', info.info_viwes.condominium.contract.contract_view.edit_contract,
         name="edit-contract"),
    path('locations/', condominium_view.locations, name="locations"),
    path('checklists/', checklist_view.checklists, name="checklists"),
    path('add-checklist/', checklist_view.add_checklist, name="add-checklist"),
    path('edit-checklist/<int:id>', checklist_view.edit_checklist, name="edit-checklist"),
    path('delete-checklist/<int:id>', checklist_view.delete_checklist, name="delete-checklist"),
    path('view-checklist/<int:id>', checklist_view.view_checklist, name="view-checklist"),
    path('clear-checklist/<int:id>', checklist_view.clear_checklist, name="clear-checklist"),
    path('resolve-task/<int:id>', checklist_view.task_completed, name="resolve-task"),
    path('report-task/<int:id>', checklist_view.add_task_problem, name="report-task"),
    path('view-task-problem/<int:id>', checklist_view.view_task_problem, name="view-task-problem"),
    path('remove-function/', info.info_viwes.condominium.informative.informative_view.delete_function_from_informative,
         name="delete-function"),
    path('remove-item/', info.info_viwes.condominium.informative.informative_view.delete_item_from_informative,
         name="delete-item"),
    path('remove-image/', info.info_viwes.condominium.informative.informative_view.delete_image_from_informative,
         name="delete-image"),
    path('remove-file/', info.info_viwes.condominium.informative.informative_view.delete_file_from_informative,
           name="delete-informative-file"),
    path('remove-video/', info.info_viwes.condominium.informative.informative_view.delete_video_from_informative,
         name="delete-video"),
    path('edit-how-to/<int:id>', info.views.edit_how_to, name="edit-how-to"),
    path('hows-to/', info.views.hows_to, name="hows-to"),
    path('check-in/<str:page>', info.info_viwes.condominium_view.check_in_page, name="check-in"),
    path('check-in/', info.info_viwes.condominium_view.user_check_in_page, name="user-check-in"),
    path('check-out/', info.info_viwes.condominium_view.user_check_out_page, name="user-check-out"),
    path('check-in-report/', report_view.export_user_control, name="check-in-report"),
    path('confirm-delete/<str:previous>/<str:next>', condominium_view.confirm_delete, name="confirm-delete"),
    path('employees/', employee_view.employees, name="employees"),
    path('add-employee/', employee_view.add_employee, name="add-employee"),
    path('delete-employee/<int:id>', employee_view.delete_employee, name="delete-employee"),
    path('view-employee/<int:id>', employee_view.view_employee, name="view-employee"),
    path('edit-employee/<int:id>', employee_view.edit_employee, name="edit-employee"),
    path('reports/', report_view.reports, name="reports"),
    path('activity-report/', report_view.activity_report, name="activity-report"),
    path('order-report/', report_view.order_report, name="order-report"),
    path('message-report/', report_view.message_report, name="message-report"),
    path('checklist-report/', report_view.checklist_report, name="checklist-report"),
    path('view-checklist-report/<int:id>', report_view.view_checklist_report, name="view-checklist-report"),
    path('survey-report/<int:id>', report_view.survey_report, name="survey-report"),
    path('export-order/<int:id>', report_view.export_order_to_pdf, name="export-order"),
    path('export-message/<int:id>', report_view.export_message_to_pdf, name="export-message"),
    path(
        "export-notification/<int:id>",
        report_view.export_notification_to_pdf,
        name="export-notification",
    ),

    path('contracts/', contract_view.contracts, name="contracts"),
    path('cancel-contract/<int:id>', contract_view.delete_contract, name="cancel-contract"),
    path('export-contracts/', report_view.export_contracts, name="export-contracts"),
    path('export-locations/', report_view.export_locations, name="export-locations"),
    path('surveys-report/', report_view.surveys_report, name="surveys-report"),
    path('export-residents/', report_view.export_residents, name="export-residents"),
    path('export-answer/<int:id>', report_view.export_answer_to_pdf, name="export-answer"),
    path('reviews-report/', report_view.reviews_report, name="reviews-report"),
    path('residents-link/', condominium_view.residents_link, name="residents-link"),
    path('survey-link/', survey_view.survey_link, name="survey-link"),
    path('my-reviews/', review_view.my_review, name="my-review"),
    path('my-surveys/', survey_view.my_survey, name="my-survey"),
    path('add-signature/', condominium_view.add_signature, name="add-signature"),
    path('add-logo/', condominium_view.add_report_logo, name="add-logo"),
    path('intercom/', intercom_view.contacts, name="contacts"),
    path('resident-visitants', apartment_view.resident_visitants, name="resident-visitants"),
    path('condominium-visitants/', apartment_view.condominium_visitants, name="condominium-visitants"),
    path('add-visitants/', apartment_view.add_visitant, name="add-visitant"),
    path('add-internal-leave/', apartment_view.add_internal_leave, name="add-internal-leave"),
    path('add-visitants-security/', apartment_view.add_visitant_security, name="add-visitant-security"),
    path('mandatory-visitants-fields/', apartment_view.visitant_mandatory_fields, name="visitant-mandatory"),
    path('visitant-arrival/<int:id>', apartment_view.visitant_arrival, name="visitant-arrival"),
    path('visitant-departure/<int:id>', apartment_view.visitant_departure, name="visitant-departure"),
    path('remove-visitant/<int:id>', apartment_view.remove_visitant, name="remove-visitant"),
    path('visitant-report/', report_view.visitant_report, name="visitant-report"),
    path('products/', product_view.products, name="products"),
    path('add-products/', product_view.add_product, name="add-product"),
    path('delete-product/<int:id>', product_view.delete_product, name="delete-product"),
    path('view-product/<int:id>', product_view.view_product, name="view-product"),
    path('edit-product/<int:id>', product_view.edit_product, name="edit-product"),
    path('storage/', storage_view.storage_management, name="storage"),
    path('storage-report/', report_view.storage_report, name="storage-report"),
    path('add-storage-entry/', storage_view.add_storage_entry, name="add-storage-entry"),
    path('withdraw-storage-entry/', storage_view.withdraw_storage_entry, name="withdraw-storage-entry"),
    path('hide-contact/', apartment_view.hide_contact, name="hide-contact"),
    path('read-notification/', views.read_notification, name="read-notification"),
    path('approve-residents/', apartment_view.approve_residents, name="approve-residents"),
    path('approve-resident/<int:id>', apartment_view.approve_resident, name="approve-resident"),
    path('view-resident/<int:id>', apartment_view.view_resident, name="view-resident"),
    path('reprove-resident/<int:id>', apartment_view.reprove_resident, name="reprove-resident"),
    path('approve-answers/<int:id>', survey_view.approve_answers, name="approve-answers"),
    path('approve-answer/<int:id>', survey_view.approve_answer, name="approve-answer"),
    path('reprove-answer/<int:id>', survey_view.reprove_answer, name="reprove-answer"),
    path('reprove-all/<int:id>', survey_view.reprove_all_answers, name="reprove-all"),
    path('approve-all/<int:id>', survey_view.approve_all_answers, name="approve-all"),
    path(
        "configure-messages/<int:id>",
        views.configure_messages,
        name="configure-messages",
    ),
    path(
        "bill-messages/<int:id>",
        views.bill_messages,
        name="bill-messages",
    ),
    path(
        "view-message-bill/<int:id>",
        views.view_message_bill,
        name="view-message-bill",
    ),
    path(
        'remove-message-bill/<int:id>',
        views.delete_message_bill,
        name="delete-message-bill"
    ),
    path(
        "messages-bills",
        views.messages_bills,
        name="messages-bills",
    ),
    path('send-bill/', condominium_view.send_bills, name="send-bill"),
    path('bills/', condominium_view.bills, name="bills"),
    path('my-bills', condominium_view.my_bills, name="my-bills"),
    path('timelines/', timeline_view.timelines, name="timelines"),
    path('add-timeline/', timeline_view.add_timeline, name="add-timeline"),
    path('add-phase/<int:id>', timeline_view.add_phase, name="add-phase"),
    path('view-timeline/<int:id>', timeline_view.view_timeline, name="view-timeline"),
    path('export-timeline/<int:id>', timeline_view.export_timeline, name="export-timeline"),
    path('remove-timeline/<int:id>', timeline_view.delete_timeline, name="remove-timeline"),
    path('update-timeline/<int:id>', timeline_view.update_timeline, name="update-timeline"),
    path('timeline-report/', report_view.timeline_report, name="timeline-report"),
    path('booking-report/', report_view.reservation_report, name="booking-report"),
    # path('valid-all-votes/', review_view.valid_all_votes, name="valid-all-votes"),
    path('add-my-activity', apartment_view.add_resident_activity, name="add-my-activity"),
    path(
        "add-maintenance-activity", condominium_view.add_condominium_maintenance_activity,
        name="add-maintenance-activity"
    ),
    path(
        "add-inspect-activity", condominium_view.add_condominium_inspect_activity, name="add-inspect-activity"
    ),
    path(
        "add-occurrence-activity", condominium_view.add_condominium_occurrence_activity, name="add-occurrence-activity"
    ),

    path('edit-my-activity/<int:id>', apartment_view.edit_resident_activity, name="edit-my-activity"),
    path('view-my-activity/<int:id>', apartment_view.view_resident_activity, name="view-my-activity"),
    path('finish-activity/<int:id>', apartment_view.finish_resident_activity, name="finish-activity"),
    path('my-activities', apartment_view.my_activities, name="my-activities"),
    path('resident-activities', condominium_view.resident_activities, name="resident-activities"),
    path('allow-departure/<int:id>', apartment_view.allow_departure, name="allow-departure"),
    path('view-reset-password/<int:id>', views.condominium_reset_password, name="view-password-reset"),
    path('confirm-reset-password/<int:id>', views.confirm_reset_password, name="confirm-reset"),
    path('admin-sign-up', administrator_view.sign_up, name="admin-sign-up"),
    path('admin-condominiums', administrator_view.condominiuns, name="admin-condominiums"),
    path('select-condominium/<int:id>', administrator_view.select_condominium, name="select-condominium"),
    path('back-condominium', administrator_view.back_admin, name="back-admin"),
    path('admin-add-condominium', administrator_view.add_condominium, name="admin-add-condominium"),
    path('admin-delete-condominium/<int:id>', administrator_view.delete_condominium, name="admin-delete-condominium"),
    path('resident-activity-report/', report_view.resident_activity_report, name="resident-activity-report"),
    path('config-dashboard/', views.config_dashboard, name="config-dashboard"),
    path('config-residents/', views.config_residents, name="config-residents"),
    path('booking/', reservation_view.booking, name="booking"),
    path('add-place/', reservation_view.add_place, name="add-place"),
    path('remove-place/<int:id>', reservation_view.delete_place, name="delete-place"),
    path('edit-place/<int:id>', reservation_view.edit_place, name="edit-place"),
    path('places/', reservation_view.places, name="places"),
    path('booking-places/', reservation_view.resident_places, name="booking-places"),
    path('my-booking', reservation_view.my_reservation, name="my-booking"),
    path('cancel-booking/<int:id>', reservation_view.cancel_reservation, name="cancel-booking"),
    path('approve-booking/<int:id>', reservation_view.approve_reservation, name="approve-booking"),
    path('validate-payment/<int:id>', reservation_view.validate_paymewnt, name="validate-payment"),
    path('delete-booking/<int:id>', reservation_view.delete_reservation, name="delete-booking"),
    path('add-time/<int:id>', reservation_view.add_time, name="add-time"),
    path('edit-time/<int:id>', reservation_view.edit_time, name="edit-time"),
    path('booking-detail/<int:id>', reservation_view.booking_detail, name="booking-detail"),
    path('place/<int:id>', reservation_view.booking_manager_detail, name="place"),
    path('booking-date/<int:id>', reservation_view.booking_date, name="booking-date"),
    path('booking/<int:place_id>/<int:time_id>/<str:date>', reservation_view.reservation, name="reservation"),
    path('hide-place/<int:id>', reservation_view.hide_place, name="hide-place"),
    path('notify-booking/<int:id>', reservation_view.notify_booking, name="notify-booking"),
    path('add-limits', reservation_view.add_condominium_limits, name="add-limit"),
    path('add-booking-bill/<int:id>', reservation_view.add_bill, name="add-booking-bill"),
    path('add-booking-payment/<int:id>', reservation_view.add_payment, name="add-booking-payment"),
    path('get-server-time/', apartment_view.get_server_time, name="get-server-time"),
    path('documents/', document_view.documents, name="documents"),
    path('add-folder/<int:parent_id>/<str:page>', document_view.add_folder, name="add-folder"),
    path('folder/<int:parent_id>', document_view.folder_detail, name="folder"),
    path('back/<int:parent_id>', document_view.folder_back, name="back-folder"),
    path('delete-folder/<int:id>', document_view.delete_folder, name="delete-folder"),
    path('edit-folder/<int:id>', document_view.edit_folder, name="edit-folder"),
    path('add-file/<int:parent_id>', document_view.add_file, name="add-file"),
    path('delete-file/<int:id>', document_view.delete_file, name="delete-file"),
    path('resident-documents/', document_view.resident_documents, name="resident-documents"),
    path('resident-folder/<int:parent_id>', document_view.resident_folder_detail, name="resident-folder"),
    path('back-resident/<int:parent_id>', document_view.folder_resident_back, name="back-resident-folder"),
    path('add-resident-from-excel', condominium_view.add_resident_from_file, name="add-resident-excel"),
    path('delete-apt', condominium_view.delete_apt, name="delete-ap"),
    path('delete-dup-visit', apartment_view.remove_duplicate_visitant, name="remove-duplicate-visitant"),
    # path('edit-image/<str:unique_id>/', informative_view.edit_image, name='edit_image'),
    # path('store-image/', informative_view.store_image, name='store_image'),

    # path('grant-permissions/', employee_view.grant_all_permissions, name="grant-permissions"),
    path('remove-permissions/', views.remove_resident_permission, name="remove-permissions"),
    path('import-permission/', views.import_permission, name="import-permission"),
    # path('resident-permissions/', condominium_view.permission_to_residents, name="resident-permissions"),
    path('resident-permissions/', views.add_user_resident_permission, name="resident-permissions"),
    path('remove-res-permissions/', views.remove_user_resident_permission, name="remove-resident-permissions"),
    path('condo-permissions/', views.add_condominium_permission, name="condo-permissions"),
    path('all-permissions/', views.grant_permission_by_profile, name="all-permissions"),
    path('check-users/', condominium_view.deactivate_expired_users, name="check-users"),
    path('aux/', views.aux, name="aux"),
    path('add-new-permissions/', views.add_new_permissions, name="add-permissions"),
    path('plate-aux/', apartment_view.aux_clean_plate, name="plate-aux"),
    path('visitants-aux', views.add_visitants_into_residents, name="visitants-aux"),
    path(
        'save-push-token/',
        firebase_view.save_push_token,
        name='save_push_token'
    ),

    path(
        'firebase-messaging-sw.js',
        firebase_view.return_firebase_worker,
        name='return-worker'
    ),

    path(
        'test-push-not/',
        firebase_view.test_user_notification,
        name='test-push'
    ),
    path(
        'clear-push-not/',
        firebase_view.clear_push_not,
        name='clear-push'
    ),
    path(
        "confirm-booking/<int:place_id>/<int:time_id>/<str:date>",
        reservation_view.confirm_reservation,
        name="confirm-reservation",
    ),

    path('.well-known/assetlinks.json', condominium_view.well_known_assets, name="assets"),
    path('policy', views.policy, name="policy"),
    # path('use-tabs', views.use_tabs, name="use-tabs"),
    # path('resident-mode', apartment_view.add_manager_resident, name="resident-mode"),
    # path('manager-mode', apartment_view.manager_mode, name="manager-mode"),
    # path('remove-kind/', informative_view.remove_kind, name="remove-kind"),
    path('reset-expi-date/', views.update_expiration, name="update-expiration"),
    path('add-default-kinds/', informative_view.add_default_activity_kinds, name="default-kinds"),
    path('remove-helps/', views.remove_helps, name="remove-helps"),
    path('visitants-aux/', apartment_view.remove_permanent_visitant, name="remove-permanent-visitants"),
    path('visitants-aux-remove/', views.remove_add_visitant_from_non_residents, name="visitants-aux-remove"),
    path('remove-booking/', views.remove_booking_permission, name="remove-booking"),
    path('aux-report/', report_view.aux_report, name="aux-report"),

    path('new-sec-perm/', views.add_new_security_perm, name="new-sec-perm"),

    path(
        'test-new',
        views.test_new,
        name="test-new"
    ),

    # AJAX function views
    path('email', views.email, name="email"),

    path('add-pedestrian', pedestrian_view.add_pedrestrian, name="add-pedestrian"),
    path('pedestrians', pedestrian_view.pedestrians, name="pedestrians"),
    path('pedestrian-view/<int:id>', pedestrian_view.view_pedestrian, name="view_pedestrian"),
    path('pedestrian-move/<int:id>', pedestrian_view.pedestrian_move, name="pedestrian-move"),
    path('pedestrian-report', report_view.pedestrian_report, name="pedestrian_report"),
    path('add-vehicle', vehicle_view.add_vehicle, name="add-vehicle"),
    path('vehicles', vehicle_view.vehicles, name="vehicles"),
    path('vehicle-view/<int:id>', vehicle_view.view_vehicle, name="view_vehicle"),
    path('vehicle-move/<int:id>', vehicle_view.vehicle_move, name="vehicle-move"),
    path('vehicle-report', report_view.vehicle_report, name="vehicle_report"),
    path(
        'export-reservation/<int:id>',
        reservation_view.export_to_pdf,
        name="export-booking"
    ),
    path(
        "confirm-resident-reset-password/<int:id>",
        apartment_view.confirm_manager_reset_password,
        name="resident-confirm-reset",
    ),
    path(
        "resident-reset-password/<int:id>",
        apartment_view.reset_password,
        name="resident-password-reset",
    ),

    path(
        "add-resident-not",
        views.add_residents_notification,
        name="add-resident-not",
    ),

    re_path(r'^verification/(?P<uidb64>.+)/(?P<token>.+)/$', views.verification, name="verification"),
    re_path(r'^review-answer/(?P<uidb64>.+)/$', review_view.add_answer, name="review-answer"),
    re_path(r'^email-verification/(?P<uidb64>.+)/(?P<token>.+)/(?P<n_email>.+)/$', condominium_view.email_verification,
            name="email-verification"),
    re_path(r'^survey-answer/(?P<uidb64>.+)/(?P<token>.+)/(?P<email>.+)/$', survey_view.add_survey_answer,
            name="survey-answer"),
    re_path(r'^anonimous-survey-answer/(?P<uidb64>.+)/(?P<token>.+)/(?P<email>.+)/$',
            survey_view.add_anonimous_survey_answer,
            name="anonimous-survey-answer"),
    re_path(r'^resident-registration/(?P<uidb64>.+)/(?P<token>.+)/$', condominium_view.add_resident_by_link,
            name="resident-registration"),
    re_path(r'^send-to/(?P<link>.+)/$', condominium_view.send_link_to, name="send-to"),
    re_path(r'^send-to-resident/(?P<link>.+)/$', condominium_view.send_link_to_resident, name="send-to-resident"),
    re_path(r'^send-to-block/(?P<link>.+)/$', condominium_view.send_link_to_block, name="send-to-block"),
    re_path(r'^send-to-all/(?P<link>.+)/$', condominium_view.send_link_to_all, name="send-to-all"),
    re_path(r'^send-to-email/(?P<link>.+)/$', condominium_view.send_link_to_email, name="send-to-email"),
    re_path(r'^export-xls/(?P<model>.+)/$', report_view.export_to_exel, name="xls-export"),
    # re_path(r'^manifest\.json$', views.manifest, name='manifest'),
    # path("about", views.AboutView.as_view(), name="about"),
    # path("contact", views.ContactView.as_view(), name="contact"),
    # path("media", views.MediaView.as_view(), name="media"),
]
