# Generated by Django 4.2.1 on 2023-05-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.block', verbose_name='Bloco'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number',
            field=models.IntegerField(verbose_name='Número'),
        ),
    ]
