# Generated by Django 4.2.1 on 2023-05-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_apartment_block_alter_apartment_complement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='kind',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
