# Generated by Django 4.2.1 on 2023-05-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_function_informative_functionitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informative',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='function',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='function',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='function',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='functionitem',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='functionitem',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='functionitem',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='functionitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='informative',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='informative',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
