# Generated by Django 4.2.1 on 2023-05-22 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_informative_created_alter_function_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.AlterField(
            model_name='functionitem',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.function', verbose_name='Função'),
        ),
        migrations.AddField(
            model_name='functionitem',
            name='images',
            field=models.ManyToManyField(to='info.imagemodel'),
        ),
    ]
