# Generated by Django 4.2.1 on 2023-05-23 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_imagemodel_alter_functionitem_function_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionitem',
            name='images',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='function_item',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='info.functionitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Imagem'),
        ),
    ]
