# Generated by Django 4.2.1 on 2023-05-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_remove_functionitem_images_imagemodel_function_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='img/', verbose_name='Imagem de fundo')),
            ],
        ),
        migrations.AddField(
            model_name='informative',
            name='cover',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.coverimagemodel'),
        ),
    ]
