# Generated by Django 4.2.1 on 2023-05-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_condominiumprofile_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionitem',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link'),
        ),
    ]
