# Generated by Django 4.2.1 on 2023-06-03 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_alter_functionitem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nome da função'),
        ),
        migrations.AlterField(
            model_name='functionitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nome do item'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Imagem do item'),
        ),
        migrations.AlterField(
            model_name='informative',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nome do informativo'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da encomenda')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('updated', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='img/', verbose_name='Imagem da encomenda')),
                ('delivered', models.DateField(blank=True, null=True)),
                ('Apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.apartment')),
            ],
        ),
    ]
