# Generated by Django 4.2.1 on 2023-06-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_alter_function_title_alter_functionitem_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagem da encomenda'),
        ),
    ]
