# Generated by Django 4.2.1 on 2023-06-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_alter_order_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
