# Generated by Django 4.2.1 on 2023-06-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_order_code_order_qrcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Apartment',
            new_name='apartment',
        ),
    ]
