# Generated by Django 4.2.1 on 2023-06-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_rename_apartment_order_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionItemFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('function_item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='info.functionitem')),
            ],
        ),
    ]
