# Generated by Django 4.2.1 on 2023-06-09 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_functionitemfilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, verbose_name='Serviço')),
                ('provider', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prestador')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated',
        ),
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condominiumprofile',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='informative',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ReviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Seu nome')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50, verbose_name='Bloco/Apartamento')),
                ('message', models.CharField(blank=True, max_length=250, null=True, verbose_name='Comentário')),
                ('rate', models.IntegerField(default=0, verbose_name='Nota')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagem')),
                ('created', models.DateField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.review')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
