# Generated by Django 4.2.1 on 2023-06-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_review_remove_order_updated_order_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='reviewanswer',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bloco/Apartamento'),
        ),
        migrations.AlterField(
            model_name='reviewanswer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reviewanswer',
            name='rate',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reviewanswer',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.review'),
        ),
    ]
