# Generated by Django 4.2.1 on 2023-06-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_surveymodel_tokenmodel_email_surveyoptionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyoptionmodel',
            name='votes',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='surveymodel',
            name='question',
            field=models.CharField(max_length=150, verbose_name='Questão'),
        ),
    ]
