# Generated by Django 4.2.1 on 2023-06-11 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_surveyoptionmodel_votes_alter_surveymodel_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymodel',
            name='condominium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveyoptionmodel',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.surveymodel'),
        ),
    ]
