# Generated by Django 4.2.1 on 2023-06-12 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_surveymodel_condominium_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Item')),
                ('description', models.CharField(blank=True, max_length=140, null=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Foto')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Última manutenção')),
                ('next_maintenance', models.DateField(blank=True, null=True, verbose_name='Próxima manutenção')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Email de quem será notificado')),
                ('days_to_notify', models.IntegerField(default=1, verbose_name='Notificar em')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
