# Generated by Django 4.2.1 on 2023-06-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='domain',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='domain'),
        ),
        migrations.AddField(
            model_name='contract',
            name='notify_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
