# Generated by Django 4.2.1 on 2023-06-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_alter_contract_days_to_notify_userlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='ip_address',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
