# Generated by Django 4.2.1 on 2023-06-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_userlocation_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
