# Generated by Django 4.2.1 on 2023-06-15 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0025_userlocation_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nome da lista')),
                ('created', models.DateField(auto_now_add=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30, verbose_name='O que vai verificar')),
                ('is_completed', models.BooleanField(default=False)),
                ('reported_problem', models.BooleanField(default=False)),
                ('problem_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição do problema')),
                ('reported_problem_image', models.ImageField(blank=True, upload_to='problem_images/')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.checklist')),
            ],
        ),
    ]
