# Generated by Django 4.2.1 on 2023-06-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_checklist_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionitemfilemodel',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='problem_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='reported_problem_image',
            field=models.ImageField(blank=True, upload_to='problem_images/', verbose_name='Foto'),
        ),
    ]
