# Generated by Django 4.2.1 on 2023-06-18 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0027_alter_functionitemfilemodel_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=250)),
                ('kind', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
