# Generated by Django 4.2.1 on 2023-06-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0028_howto'),
    ]

    operations = [
        migrations.AddField(
            model_name='informative',
            name='kind',
            field=models.CharField(default='Informativo', max_length=13),
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagem da correspondência'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Correspondência recebida'),
        ),
    ]
