# Generated by Django 4.2.1 on 2023-06-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0029_informative_kind_alter_order_image_alter_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collected_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Recebido por'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Entregue por'),
        ),
        migrations.AddField(
            model_name='order',
            name='received_by',
            field=models.CharField(default='Funcionário local', max_length=50, verbose_name='Recebido por'),
        ),
        migrations.AlterField(
            model_name='informative',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nome da Atividade'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
