# Generated by Django 4.2.1 on 2023-06-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0030_order_collected_by_order_delivered_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='collected_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Retirado por'),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Recebido por'),
        ),
    ]
