# Generated by Django 4.2.1 on 2023-06-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0031_alter_order_collected_by_alter_order_received_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='collected_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Recebido por'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Recebido em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entregue em'),
        ),
    ]
