# Generated by Django 4.2.1 on 2023-06-22 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0032_alter_order_collected_by_alter_order_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(blank=True, max_length=16, null=True)),
                ('apartment', models.CharField(blank=True, max_length=16, null=True)),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
                ('kind', models.CharField(blank=True, max_length=15, null=True)),
                ('to_list', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='Arquivo')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.message')),
            ],
        ),
    ]
