# Generated by Django 4.2.1 on 2023-06-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0033_message_messagefilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='item',
            field=models.CharField(max_length=50, verbose_name='Nome do item'),
        ),
        migrations.AlterField(
            model_name='informative',
            name='kind',
            field=models.CharField(default='Informativo', max_length=25),
        ),
        migrations.AlterField(
            model_name='informative',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nome ou local da atividade'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome da correspondência'),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_by',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Funcionário que recebeu a correspondência'),
        ),
    ]
