# Generated by Django 4.2.1 on 2023-06-24 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0034_alter_contract_item_alter_informative_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominiumprofile',
            name='work_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
