# Generated by Django 4.2.1 on 2023-06-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0035_condominiumprofile_work_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howto',
            name='value',
            field=models.CharField(max_length=500),
        ),
    ]
