# Generated by Django 4.2.1 on 2023-06-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0036_alter_howto_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominiumprofile',
            name='is_testing',
            field=models.BooleanField(default=True),
        ),
    ]
