# Generated by Django 4.2.1 on 2023-07-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0037_condominiumprofile_is_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='description',
        ),
        migrations.RemoveField(
            model_name='function',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='functionitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='functionitem',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='informative',
            name='cover',
        ),
        migrations.AlterField(
            model_name='functionitem',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.DeleteModel(
            name='CoverImageModel',
        ),
    ]
