# Generated by Django 4.2.1 on 2023-07-01 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0038_remove_function_description_remove_function_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionitem',
            name='link',
        ),
        migrations.CreateModel(
            name='FunctionItemVideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link pro vídeo')),
                ('function_item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='info.functionitem')),
            ],
        ),
    ]
