# Generated by Django 4.2.1 on 2023-07-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0039_remove_functionitem_link_functionitemvideolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
