# Generated by Django 4.2.1 on 2023-07-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0040_alter_userlocation_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informative',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
