# Generated by Django 4.2.1 on 2023-07-22 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0042_surveymodel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominiumprofile',
            name='resident_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='informative',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='DESCRIÇÃO'),
        ),
        migrations.AlterField(
            model_name='informative',
            name='title',
            field=models.CharField(max_length=200, verbose_name='NOME OU LOCAL DA ATIVIDADE'),
        ),
        migrations.AlterField(
            model_name='review',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='review',
            name='service',
            field=models.CharField(max_length=50, verbose_name='Item a ser avaliado'),
        ),
    ]
