# Generated by Django 4.2.1 on 2023-07-23 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0043_condominiumprofile_resident_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='allowed_users',
            field=models.ManyToManyField(related_name='recipients', to=settings.AUTH_USER_MODEL),
        ),
    ]
