# Generated by Django 4.2.1 on 2023-07-23 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0044_review_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipients', to=settings.AUTH_USER_MODEL),
        ),
    ]
