# Generated by Django 4.2.1 on 2023-07-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0046_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
