# Generated by Django 4.2.1 on 2023-07-30 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0047_resident_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(blank=True, max_length=16, null=True, verbose_name='Autorizado para o Bloco')),
                ('apartment', models.CharField(blank=True, max_length=16, null=True, verbose_name='Autorizado para o Apartamento')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Visitante')),
                ('document', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número do documento do Visitante')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Obcervações')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('until', models.DateTimeField(blank=True, null=True, verbose_name='Autorizado até')),
                ('allowed', models.BooleanField(default=True)),
                ('security_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Porteiro que liberou')),
                ('visit_in', models.DateTimeField(blank=True, null=True, verbose_name='Liberado pela Portaria em')),
                ('photo', models.ImageField(blank=True, upload_to='visitants/', verbose_name='Foto do visitante')),
                ('vehicle_model', models.CharField(blank=True, max_length=20, null=True, verbose_name='Modelo do Veículo')),
                ('vehicle_plate', models.CharField(blank=True, max_length=8, null=True, verbose_name='Placa do Veículo')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
