# Generated by Django 4.2.1 on 2023-07-30 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0048_visitant'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitant',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident', to=settings.AUTH_USER_MODEL),
        ),
    ]
