# Generated by Django 4.2.1 on 2023-07-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0049_visitant_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitant',
            name='leaves_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Saída em'),
        ),
    ]
