# Generated by Django 4.2.1 on 2023-07-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0051_visitantreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitantreport',
            name='photo',
            field=models.ImageField(blank=True, upload_to='report-visitants/', verbose_name='Foto do visitante'),
        ),
    ]
