# Generated by Django 4.2.1 on 2023-08-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0054_alter_product_image_storageentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='storageentry',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Preço por unidade em R$:'),
        ),
        migrations.AlterField(
            model_name='storageentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.product', verbose_name='Selecione o Produto'),
        ),
    ]
