# Generated by Django 4.2.1 on 2023-08-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0055_product_quantity_alter_storageentry_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warning_quantity',
            field=models.IntegerField(default=0, verbose_name='Avisar quando quantidade for menor que'),
        ),
    ]
