# Generated by Django 4.2.1 on 2023-08-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0056_product_warning_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominiumprofile',
            name='hide_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='warning_quantity',
            field=models.IntegerField(default=1, verbose_name='Avisar quando quantidade for menor que'),
        ),
    ]
