# Generated by Django 4.2.1 on 2023-08-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0057_condominiumprofile_hide_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='hide_contact',
            field=models.BooleanField(default=False),
        ),
    ]
