# Generated by Django 4.2.1 on 2023-08-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0059_norification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Norification',
            new_name='Notification',
        ),
    ]
