# Generated by Django 4.2.1 on 2023-08-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0060_rename_norification_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
