# Generated by Django 4.2.1 on 2023-08-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0061_notification_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Nome do Bloco/Quadra/Setor'),
        ),
        migrations.AlterField(
            model_name='visitant',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome do Visitante ou Encomenda'),
        ),
    ]
