# Generated by Django 4.2.1 on 2023-08-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0062_alter_apartment_complement_alter_block_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitant',
            name='check_photo',
            field=models.ImageField(blank=True, upload_to='visitants/', verbose_name='Foto/Documento do visitante'),
        ),
    ]
