# Generated by Django 4.2.1 on 2023-08-30 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0064_informativekind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, verbose_name='Item a ser avaliado')),
                ('provider', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.review')),
            ],
        ),
    ]
