# Generated by Django 4.2.1 on 2023-08-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0065_reviewitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='service',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Item a ser avaliado'),
        ),
    ]
