# Generated by Django 4.2.1 on 2023-08-30 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0066_alter_review_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewanswer',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.reviewitem'),
        ),
    ]
