# Generated by Django 4.2.1 on 2023-08-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0067_reviewanswer_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagem'),
        ),
    ]
