# Generated by Django 4.2.1 on 2023-09-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0068_reviewitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominiumprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Sua foto'),
        ),
    ]
