# Generated by Django 4.2.1 on 2023-09-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0069_condominiumprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominiumprofile',
            name='added_by_link',
            field=models.BooleanField(default=False),
        ),
    ]
