# Generated by Django 4.2.1 on 2023-09-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0070_condominiumprofile_added_by_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewanswer',
            name='answer_pic',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Sua foto'),
        ),
        migrations.AddField(
            model_name='reviewanswer',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
