# Generated by Django 4.2.1 on 2023-09-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0071_reviewanswer_answer_pic_reviewanswer_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewanswer',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='reported_problem_image',
            field=models.ImageField(blank=True, upload_to='problem_images/', verbose_name='Selecione uma foto da sua Galeria'),
        ),
        migrations.CreateModel(
            name='SurveyAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False)),
                ('answer_pic', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Sua foto')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.surveyoptionmodel')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.surveymodel')),
            ],
        ),
    ]
