# Generated by Django 4.2.1 on 2023-09-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0072_alter_reviewanswer_is_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswermodel',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bloco/Apartamento'),
        ),
        migrations.AddField(
            model_name='surveyanswermodel',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Seu nome'),
            preserve_default=False,
        ),
    ]
