# Generated by Django 4.2.1 on 2023-09-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0073_surveyanswermodel_address_surveyanswermodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
