# Generated by Django 4.2.1 on 2023-09-13 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0074_surveyanswermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswermodel',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
