# Generated by Django 4.2.1 on 2023-09-16 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0075_surveyanswermodel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveymodel',
            name='allowed_users',
            field=models.ManyToManyField(related_name='survey_recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='allowed_users',
            field=models.ManyToManyField(related_name='recipients', to=settings.AUTH_USER_MODEL),
        ),
    ]
