# Generated by Django 4.2.1 on 2023-09-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0076_surveymodel_allowed_users_alter_review_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenmodel',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.surveymodel'),
        ),
    ]
