# Generated by Django 4.2.1 on 2023-09-16 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0077_tokenmodel_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyoptionmodel',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyanswermodel',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.surveyoptionmodel', verbose_name='Voto em'),
        ),
        migrations.AlterField(
            model_name='surveyanswermodel',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.surveymodel', verbose_name='Enquete'),
        ),
    ]
