# Generated by Django 4.2.1 on 2023-09-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0078_surveyoptionmodel_is_ended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyoptionmodel',
            name='is_ended',
        ),
        migrations.AddField(
            model_name='surveymodel',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
