# Generated by Django 4.2.1 on 2023-09-17 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0079_remove_surveyoptionmodel_is_ended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.userlocation'),
        ),
        migrations.AddField(
            model_name='informativekind',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.userlocation'),
        ),
        migrations.AddField(
            model_name='surveymodel',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.userlocation'),
        ),
    ]
