# Generated by Django 4.2.1 on 2023-09-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0080_checklist_location_informativekind_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informativekind',
            name='location',
        ),
        migrations.AddField(
            model_name='informative',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.userlocation'),
        ),
    ]
