# Generated by Django 4.2.1 on 2023-09-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0081_remove_informativekind_location_informative_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='location',
            new_name='creation_location',
        ),
        migrations.AddField(
            model_name='checklist',
            name='check_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_location', to='info.userlocation'),
        ),
    ]
