# Generated by Django 4.2.1 on 2023-09-17 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0082_rename_location_checklist_creation_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='creation_location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='check_location',
        ),
        migrations.AddField(
            model_name='task',
            name='ocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.userlocation'),
        ),
    ]
