# Generated by Django 4.2.1 on 2023-09-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0083_rename_creation_location_checklist_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='ocation',
            new_name='location',
        ),
    ]
