# Generated by Django 4.2.1 on 2023-09-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0086_bill_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='sender',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
