# Generated by Django 4.2.1 on 2023-09-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0087_bill_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominiumprofile',
            name='profile',
            field=models.CharField(blank=True, default='main', max_length=15, null=True),
        ),
    ]
