# Generated by Django 4.2.1 on 2023-09-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0089_timeline_timelinefase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimelineFase',
            new_name='TimelinePhase',
        ),
    ]
