# Generated by Django 4.2.1 on 2023-09-29 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0090_rename_timelinefase_timelinephase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='end_date',
            field=models.DateField(verbose_name='Data final'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='start_date',
            field=models.DateField(verbose_name='Data de ínicio'),
        ),
        migrations.AlterField(
            model_name='timelinephase',
            name='end_date',
            field=models.DateField(verbose_name='Data de entrega'),
        ),
        migrations.AlterField(
            model_name='timelinephase',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
