# Generated by Django 4.2.1 on 2023-09-29 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0091_alter_timeline_end_date_alter_timeline_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
