# Generated by Django 4.2.1 on 2023-10-05 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0092_alter_timeline_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nome da função')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link pro vídeo')),
                ('informative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.informative')),
            ],
        ),
        migrations.AlterField(
            model_name='functionitemfilemodel',
            name='function_item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='info.activityfunction'),
        ),
        migrations.AlterField(
            model_name='functionitemvideolink',
            name='function_item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='info.activityfunction'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='function_item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='info.activityfunction'),
        ),
    ]
