# Generated by Django 4.2.1 on 2023-10-28 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0093_activityfunction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=13)),
                ('protocol', models.CharField(max_length=13)),
                ('title', models.CharField(max_length=60, verbose_name='Título')),
                ('description', models.CharField(max_length=250, verbose_name='Descrição')),
                ('resident', models.CharField(blank=True, max_length=150, null=True, verbose_name='Morador')),
                ('responsible', models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsável')),
                ('status', models.CharField(max_length=13)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.apartment')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='signature',
            name='image',
            field=models.ImageField(blank=True, upload_to='signature/', verbose_name='Selecione a imagem da sua assinatura de email'),
        ),
        migrations.CreateModel(
            name='ResidentActivityAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250, verbose_name='Mensagem')),
                ('auteur', models.CharField(blank=True, max_length=150, null=True, verbose_name='Autor')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.residentactivity')),
            ],
        ),
    ]
