# Generated by Django 4.2.1 on 2023-11-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0094_residentactivity_alter_signature_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominiumprofile',
            name='auto_aprove',
            field=models.BooleanField(default=False),
        ),
    ]
