# Generated by Django 4.2.1 on 2023-11-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0095_condominiumprofile_auto_aprove'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condominiumprofile',
            old_name='auto_aprove',
            new_name='auto_approve',
        ),
    ]
