# Generated by Django 4.2.1 on 2023-11-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0096_rename_auto_aprove_condominiumprofile_auto_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitant',
            name='can_leave',
            field=models.BooleanField(default=False),
        ),
    ]
