# Generated by Django 4.2.1 on 2023-11-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0097_visitant_can_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitant',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
    ]
