# Generated by Django 4.2.1 on 2023-11-22 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0098_visitant_arrived'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominiumprofile',
            name='is_administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='condominiumprofile',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='condominiumprofile',
            name='condominium_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
