# Generated by Django 4.2.1 on 2023-11-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0099_condominiumprofile_is_administrator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominiumprofile',
            name='selected',
            field=models.IntegerField(default=0),
        ),
    ]
