# Generated by Django 4.2.1 on 2023-11-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0100_condominiumprofile_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinephase',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='timelines-phases/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='timelinephase',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link pro vídeo'),
        ),
    ]
