# Generated by Django 4.2.1 on 2023-11-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0101_timelinephase_image_timelinephase_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominiumprofile',
            name='use_tabs',
            field=models.BooleanField(default=False),
        ),
    ]
