# Generated by Django 4.2.1 on 2023-11-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0102_condominiumprofile_use_tabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominiumprofile',
            name='use_tabs',
            field=models.BooleanField(default=True),
        ),
    ]
