# Generated by Django 4.2.1 on 2023-12-20 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0103_alter_condominiumprofile_use_tabs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('rules', models.FileField(blank=True, null=True, upload_to='rules/', verbose_name='Regras')),
                ('inspection', models.FileField(blank=True, null=True, upload_to='inspections/', verbose_name='Termo de Vistoria')),
                ('minimum_days_to_cancel', models.IntegerField(default=0)),
                ('internal_regime', models.FileField(blank=True, null=True, upload_to='internal/', verbose_name='Regime interno')),
                ('acceptance_terms', models.FileField(blank=True, null=True, upload_to='acceptance/', verbose_name='Termo de Aceitação')),
                ('maximum_unity_reservation_per_day', models.IntegerField(default=10)),
                ('maximum_resident_reservation_per_day', models.IntegerField(default=10)),
                ('maximum_unity_reservation_per_month', models.IntegerField(default=10)),
                ('maximum_resident_reservation_per_month', models.IntegerField(default=10)),
                ('maximum_unity_reservation_per_your', models.IntegerField(default=10)),
                ('maximum_resident_reservation_per_year', models.IntegerField(default=10)),
                ('minimum_days_to_reserve', models.IntegerField(default=0)),
                ('auto_confirmation', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/', verbose_name='Imagem do local')),
                ('multi_reservations', models.BooleanField()),
                ('hidden', models.BooleanField()),
                ('blocked_areas', models.ManyToManyField(blank=True, null=True, related_name='blocked_areas', to='info.place')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('blocked', models.BooleanField()),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.place')),
            ],
        ),
    ]
