# Generated by Django 4.2.1 on 2024-01-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0104_place_reservationtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='maximum_unity_reservation_per_your',
        ),
        migrations.AddField(
            model_name='place',
            name='maximum_unity_reservation_per_year',
            field=models.IntegerField(default=10, verbose_name='Máximo de reservas pela unidade por ano'),
        ),
        migrations.AlterField(
            model_name='place',
            name='auto_confirmation',
            field=models.BooleanField(default=False, verbose_name='Confirmação automãtica?'),
        ),
        migrations.AlterField(
            model_name='place',
            name='blocked_areas',
            field=models.ManyToManyField(blank=True, null=True, related_name='blocked_areas', to='info.place', verbose_name='Ãreas bloqueadas após reserva'),
        ),
        migrations.AlterField(
            model_name='place',
            name='capacity',
            field=models.IntegerField(default=0, verbose_name='Capacidade'),
        ),
        migrations.AlterField(
            model_name='place',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Ocultar lugar?'),
        ),
        migrations.AlterField(
            model_name='place',
            name='maximum_resident_reservation_per_day',
            field=models.IntegerField(default=10, verbose_name='Máximo de reservas pelo morador por dia'),
        ),
        migrations.AlterField(
            model_name='place',
            name='maximum_resident_reservation_per_month',
            field=models.IntegerField(default=10, verbose_name='Máximo de reservas pelo morador por mês'),
        ),
        migrations.AlterField(
            model_name='place',
            name='maximum_resident_reservation_per_year',
            field=models.IntegerField(default=10, verbose_name='Máximo de reservas pelo morador por ano'),
        ),
        migrations.AlterField(
            model_name='place',
            name='maximum_unity_reservation_per_day',
            field=models.IntegerField(default=10, verbose_name='Máximo de reservas pela unidade por dia'),
        ),
        migrations.AlterField(
            model_name='place',
            name='maximum_unity_reservation_per_month',
            field=models.IntegerField(default=10, verbose_name='Máximo de reservas pela unidade por mês'),
        ),
        migrations.AlterField(
            model_name='place',
            name='minimum_days_to_cancel',
            field=models.IntegerField(default=0, verbose_name='Quantidade mínima de dias para cancelar'),
        ),
        migrations.AlterField(
            model_name='place',
            name='minimum_days_to_reserve',
            field=models.IntegerField(default=0, verbose_name='Quantidade de dias de antecedência'),
        ),
        migrations.AlterField(
            model_name='place',
            name='multi_reservations',
            field=models.BooleanField(default=False, verbose_name='Permite multiplas reservas?'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome do Local'),
        ),
        migrations.AlterField(
            model_name='place',
            name='price',
            field=models.FloatField(default=0, verbose_name='Preço da reserva'),
        ),
    ]
