# Generated by Django 4.2.1 on 2024-01-04 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0105_remove_place_maximum_unity_reservation_per_your_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationtime',
            name='blocked',
            field=models.BooleanField(verbose_name='Horário Bloqueado?'),
        ),
        migrations.AlterField(
            model_name='reservationtime',
            name='end_time',
            field=models.TimeField(verbose_name='Fim da Reserva'),
        ),
        migrations.AlterField(
            model_name='reservationtime',
            name='init_time',
            field=models.TimeField(verbose_name='Início da Reserva'),
        ),
        migrations.AlterField(
            model_name='reservationtime',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.place', verbose_name='Local'),
        ),
    ]
