# Generated by Django 4.2.1 on 2024-01-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0106_alter_reservationtime_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationtime',
            name='day',
            field=models.CharField(blank=True, max_length=57, null=True, verbose_name='Dia da Semana'),
        ),
    ]
