# Generated by Django 4.2.1 on 2024-01-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0107_reservationtime_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='allow_new_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='inspection',
            field=models.FileField(blank=True, null=True, upload_to='inspections/', verbose_name='Vistoria do espaço Reservado'),
        ),
    ]
