# Generated by Django 4.2.1 on 2024-01-20 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0108_place_allow_new_reservation_alter_place_inspection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationtime',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.place', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='reviewanswer',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comentário'),
        ),
        migrations.CreateModel(
            name='BlockedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_day', models.DateTimeField()),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
