# Generated by Django 4.2.1 on 2024-01-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0109_alter_reservationtime_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedday',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.place'),
        ),
    ]
