# Generated by Django 4.2.1 on 2024-01-20 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0110_blockedday_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=13)),
                ('guests', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Lista de Convidados')),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField()),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.place')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_by', to=settings.AUTH_USER_MODEL)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.reservationtime')),
            ],
        ),
    ]
