# Generated by Django 4.2.1 on 2024-01-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0111_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
