# Generated by Django 4.2.1 on 2024-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0112_place_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='maximum_days_to_booking',
            field=models.IntegerField(default=0, verbose_name='Quantidade máxima de dias de antecedência'),
        ),
        migrations.AddField(
            model_name='place',
            name='maximum_resident_reservation_per_week',
            field=models.IntegerField(default=10, verbose_name='Máximo de reservas pelo morador por semana'),
        ),
        migrations.AddField(
            model_name='place',
            name='maximum_unity_reservation_per_week',
            field=models.IntegerField(default=10, verbose_name='Máximo de reservas pela unidade por semana'),
        ),
    ]
