# Generated by Django 4.2.1 on 2024-01-27 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0113_place_maximum_days_to_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='maximum_days_to_booking',
            field=models.IntegerField(default=60, verbose_name='Quantidade máxima de dias de antecedência'),
        ),
    ]
