# Generated by Django 4.2.1 on 2024-01-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0114_reservation_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockedday',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim da Reserva'),
        ),
        migrations.AddField(
            model_name='blockedday',
            name='init_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Início da Reserva'),
        ),
    ]
