# Generated by Django 4.2.1 on 2024-02-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0115_blockedday_end_time_blockedday_init_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='allow_new_reservation',
            field=models.IntegerField(default=0),
        ),
    ]
