# Generated by Django 4.2.1 on 2024-02-10 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0116_alter_place_allow_new_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='maximum_resident_reservation_per_day',
            field=models.IntegerField(default=10, verbose_name='Máximo de reservas nesta área pelo morador por dia'),
        ),
        migrations.AlterField(
            model_name='place',
            name='maximum_resident_reservation_per_month',
            field=models.IntegerField(default=10, verbose_name='Máximo de reservas nesta área pelo morador por mês'),
        ),
        migrations.AlterField(
            model_name='place',
            name='maximum_resident_reservation_per_week',
            field=models.IntegerField(default=10, verbose_name='Máximo de reservas nesta área pelo morador por semana'),
        ),
        migrations.AlterField(
            model_name='place',
            name='maximum_resident_reservation_per_year',
            field=models.IntegerField(default=10, verbose_name='Máximo de reservas nesta área pelo morador por ano'),
        ),
        migrations.AlterField(
            model_name='place',
            name='maximum_unity_reservation_per_day',
            field=models.IntegerField(default=10, verbose_name='Máximo de reservas nesta área pela unidade por dia'),
        ),
        migrations.AlterField(
            model_name='place',
            name='maximum_unity_reservation_per_month',
            field=models.IntegerField(default=10, verbose_name='Máximo de reservas nesta área pela unidade por mês'),
        ),
        migrations.AlterField(
            model_name='place',
            name='maximum_unity_reservation_per_week',
            field=models.IntegerField(default=10, verbose_name='Máximo de reservas nesta área pela unidade por semana'),
        ),
        migrations.AlterField(
            model_name='place',
            name='maximum_unity_reservation_per_year',
            field=models.IntegerField(default=10, verbose_name='Máximo de reservas nesta área pela unidade por ano'),
        ),
        migrations.CreateModel(
            name='CondominiumReservationLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum_unity_reservation_per_day', models.IntegerField(default=10, verbose_name='Máximo de reservas pela unidade por dia')),
                ('maximum_resident_reservation_per_day', models.IntegerField(default=10, verbose_name='Máximo de reservas pelo morador por dia')),
                ('maximum_unity_reservation_per_week', models.IntegerField(default=10, verbose_name='Máximo de reservas pela unidade por semana')),
                ('maximum_resident_reservation_per_week', models.IntegerField(default=10, verbose_name='Máximo de reservas pelo morador por semana')),
                ('maximum_unity_reservation_per_month', models.IntegerField(default=10, verbose_name='Máximo de reservas pela unidade por mês')),
                ('maximum_resident_reservation_per_month', models.IntegerField(default=10, verbose_name='Máximo de reservas pelo morador por mês')),
                ('maximum_unity_reservation_per_year', models.IntegerField(default=10, verbose_name='Máximo de reservas pela unidade por ano')),
                ('maximum_resident_reservation_per_year', models.IntegerField(default=10, verbose_name='Máximo de reservas pelo morador por ano')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
