# Generated by Django 4.2.1 on 2024-02-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0117_alter_place_maximum_resident_reservation_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='bill',
            field=models.FileField(blank=True, null=True, upload_to='reservation_bill/', verbose_name='Boleto de cobrança'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='wait_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link para cobrança'),
        ),
    ]
