# Generated by Django 4.2.1 on 2024-02-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0118_reservation_bill_reservation_wait_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment',
            field=models.FileField(blank=True, null=True, upload_to='payments/', verbose_name='Anexar comprovante de pagamento'),
        ),
    ]
