# Generated by Django 4.2.1 on 2024-02-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0119_reservation_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='canceled_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
