# Generated by Django 4.2.1 on 2024-02-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0120_reservation_approved_by_reservation_canceled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='canceled_by',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
