# Generated by Django 4.2.1 on 2024-02-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0121_alter_reservation_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.CharField(default='', max_length=250, verbose_name='Descrição'),
        ),
    ]
