# Generated by Django 4.2.1 on 2024-02-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0122_place_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='removed_by_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='removed_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
