# Generated by Django 4.2.1 on 2024-02-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0123_reservation_removed_by_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominiumprofile',
            name='defaulter',
            field=models.BooleanField(default=False),
        ),
    ]
