# Generated by Django 4.2.1 on 2024-02-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0124_condominiumprofile_defaulter'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='defaulter',
            field=models.BooleanField(default=False),
        ),
    ]
