# Generated by Django 4.2.1 on 2024-02-29 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0125_resident_defaulter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitant',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Visitante ou Encomenda'),
        ),
        migrations.CreateModel(
            name='VisitantRequiredFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BooleanField(default=False)),
                ('block', models.BooleanField(default=False)),
                ('apartment', models.BooleanField(default=False)),
                ('until', models.BooleanField(default=False)),
                ('comment', models.BooleanField(default=False)),
                ('document', models.BooleanField(default=False)),
                ('vehicle_model', models.BooleanField(default=False)),
                ('vehicle_plate', models.BooleanField(default=False)),
                ('photo', models.BooleanField(default=False, verbose_name='Enviar foto da galeria')),
                ('pic', models.BooleanField(default=False, verbose_name='Tirar foto na hora')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
