# Generated by Django 4.2.1 on 2024-03-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0126_alter_visitant_name_visitantrequiredfields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitantrequiredfields',
            old_name='apartment',
            new_name='security_name',
        ),
        migrations.RemoveField(
            model_name='visitantrequiredfields',
            name='block',
        ),
        migrations.RemoveField(
            model_name='visitantrequiredfields',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='visitantrequiredfields',
            name='name',
        ),
        migrations.RemoveField(
            model_name='visitantrequiredfields',
            name='until',
        ),
        migrations.AlterField(
            model_name='visitantrequiredfields',
            name='photo',
            field=models.BooleanField(default=True, verbose_name='Enviar foto da galeria'),
        ),
    ]
