# Generated by Django 4.2.1 on 2024-03-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0127_rename_apartment_visitantrequiredfields_security_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitantrequiredfields',
            name='document',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='visitantrequiredfields',
            name='security_name',
            field=models.BooleanField(default=True),
        ),
    ]
