# Generated by Django 4.2.1 on 2024-03-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0128_alter_visitantrequiredfields_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitant',
            name='visit_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visitant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='visitants/', verbose_name='Imagem do visitante'),
        ),
    ]
