# Generated by Django 4.2.1 on 2024-03-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0129_visitant_visit_time_alter_visitant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitant',
            name='visit_time',
            field=models.DurationField(null=True),
        ),
    ]
