# Generated by Django 4.2.1 on 2024-03-09 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0131_alter_visitant_visit_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('ip_address', models.CharField(max_length=16)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('session_time', models.DurationField(blank=True, null=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
