# Generated by Django 4.2.1 on 2024-03-09 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0133_alter_usercontrol_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontrol',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checked_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
