# Generated by Django 4.2.1 on 2024-03-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0134_usercontrol_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontrol',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
