# Generated by Django 4.2.1 on 2024-03-09 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0135_alter_usercontrol_check_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.BooleanField(default=True)),
                ('survey', models.BooleanField(default=True)),
                ('bills', models.BooleanField(default=True)),
                ('visitant', models.BooleanField(default=True)),
                ('activity', models.BooleanField(default=True)),
                ('booking', models.BooleanField(default=True)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
