# Generated by Django 4.2.1 on 2024-03-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0137_folder_localfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentfeatures',
            name='documents',
            field=models.BooleanField(default=True),
        ),
    ]
