# Generated by Django 4.2.3 on 2024-05-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0139_reportlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyoptionmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Sua foto'),
        ),
        migrations.AddField(
            model_name='surveyoptionmodel',
            name='is_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='condominiumprofile',
            name='use_tabs',
            field=models.BooleanField(default=False),
        ),
    ]
