# Generated by Django 4.2.3 on 2024-06-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0140_surveyoptionmodel_image_surveyoptionmodel_is_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do Bloco/Quadra/Setor'),
        ),
    ]
