# Generated by Django 4.2.3 on 2024-09-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0141_alter_block_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitantrequiredfields',
            name='allow_vehicle',
            field=models.BooleanField(default=True),
        ),
    ]
