# Generated by Django 4.2.3 on 2024-09-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0143_paramchanges'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitant',
            name='leave_consent',
            field=models.BooleanField(default=False),
        ),
    ]
