# Generated by Django 4.2.3 on 2024-12-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0144_visitant_leave_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentfeatures',
            name='permanent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='condominiumprofile',
            name='use_tabs',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ParamChanges',
        ),
    ]
