# Generated by Django 4.2.3 on 2025-02-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0145_residentfeatures_permanent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentactivity',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='residentactivity',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='residentactivityanswer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='img/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='residentactivityanswer',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Link'),
        ),
    ]
