# Generated by Django 5.1.7 on 2025-03-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0146_residentactivity_image_residentactivity_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominiumprofile',
            name='whatsapp_notification',
            field=models.BooleanField(default=False),
        ),
    ]
