# Generated by Django 5.1.7 on 2025-05-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0147_condominiumprofile_whatsapp_notification"),
        ("info", "0148_notification_created_notification_title_and_more"),
    ]

    operations = []
