# Generated by Django 4.2.1 on 2025-03-30 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0147_condominiumprofile_whatsapp_notification'),
        ('info', '0148_notification_created_notification_title_and_more'),
    ]

    operations = [
    ]
