# Generated by Django 5.1.7 on 2025-05-24 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0149_merge_20250524_1034"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedestrian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protocol", models.CharField(max_length=13)),
                ("name", models.CharField(max_length=60)),
                ("document", models.CharField(max_length=20)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="pedestrian/", verbose_name="Foto"
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        upload_to="pedestrian/", verbose_name="Anexar documento"
                    ),
                ),
                (
                    "destination",
                    models.CharField(max_length=50, verbose_name="Vai para onde"),
                ),
                (
                    "authorized_by",
                    models.CharField(max_length=50, verbose_name="Autorizado por"),
                ),
                ("obs", models.CharField(max_length=50, verbose_name="Observação")),
                ("send_email", models.BooleanField(default=False)),
                ("send_whatsapp", models.BooleanField(default=False)),
                ("arrived", models.BooleanField(default=False)),
                (
                    "condominium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
