# Generated by Django 5.1.7 on 2025-05-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0150_pedestrian"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedestrian",
            name="obs",
            field=models.CharField(max_length=200, verbose_name="Observação"),
        ),
    ]
