# Generated by Django 5.1.7 on 2025-05-24 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0151_alter_pedestrian_obs"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedestrian",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
