# Generated by Django 5.1.7 on 2025-05-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0152_pedestrian_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedestrian",
            name="has_leaved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pedestrian",
            name="arrived",
            field=models.BooleanField(default=True),
        ),
    ]
