# Generated by Django 5.1.7 on 2025-05-31 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0153_pedestrian_has_leaved_alter_pedestrian_arrived"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedestrian",
            name="leaved_in",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
