# Generated by Django 4.2.1 on 2025-05-31 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0149_merge_20250330_0559'),
        ('info', '0154_pedestrian_leaved_in'),
    ]

    operations = [
    ]
