# Generated by Django 5.1.7 on 2025-05-31 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0155_merge_20250531_1701"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protocol", models.CharField(max_length=13)),
                ("name", models.CharField(max_length=60)),
                ("document", models.CharField(max_length=20)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="vehicle/", verbose_name="Foto"
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        upload_to="vehicle/", verbose_name="Anexar documento"
                    ),
                ),
                (
                    "destination",
                    models.CharField(max_length=50, verbose_name="Vai para onde"),
                ),
                (
                    "authorized_by",
                    models.CharField(max_length=50, verbose_name="Autorizado por"),
                ),
                ("obs", models.CharField(max_length=200, verbose_name="Observação")),
                ("send_email", models.BooleanField(default=False)),
                ("send_whatsapp", models.BooleanField(default=False)),
                ("arrived", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("has_leaved", models.BooleanField(default=False)),
                ("leaved_in", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Veículo"
                    ),
                ),
                (
                    "vehicle_plate",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Placa"
                    ),
                ),
                (
                    "condominium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
