# Generated by Django 5.1.7 on 2025-06-14 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0156_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessagesInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "messages_limit",
                    models.IntegerField(
                        default=1000, verbose_name="Mensagens gratúitas"
                    ),
                ),
                ("messages_used", models.IntegerField(default=0)),
                (
                    "price",
                    models.FloatField(
                        default=0.1, verbose_name="Preço por mensagem em R$"
                    ),
                ),
                ("allow_charge", models.BooleanField(default=True)),
                (
                    "condominium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessagesPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("messages_used", models.IntegerField(default=0)),
                (
                    "price",
                    models.FloatField(
                        default=0.1, verbose_name="Preço por mensagem em R$"
                    ),
                ),
                (
                    "bill",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="files/",
                        verbose_name="Cobrança",
                    ),
                ),
                (
                    "payment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="files/",
                        verbose_name="Comprovante",
                    ),
                ),
                ("payed", models.BooleanField(default=False)),
                (
                    "condominium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
