# Generated by Django 5.1.7 on 2025-06-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0157_messagesinformation_messagespayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="addressee",
            field=models.CharField(
                blank=True,
                default="Não informado",
                max_length=200,
                null=True,
                verbose_name="Morador destinatário",
            ),
        ),
    ]
