# Generated by Django 5.1.7 on 2025-06-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0158_order_addressee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description",
            field=models.TextField(
                default="", max_length=250, verbose_name="Descrição"
            ),
        ),
    ]
