# Generated by Django 5.1.6 on 2025-07-05 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0159_alter_place_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notify',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ResidentActivityFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/resident_activities/', verbose_name='Arquivo')),
                ('resident_activity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='info.residentactivity')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/', verbose_name='Imagem')),
                ('resident_activity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='info.residentactivity')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentActivityKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tipo da solicitação')),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
