# Generated by Django 4.2.3 on 2025-07-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0160_message_notify_residentactivityfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentactivity',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.apartment'),
        ),
    ]
