# Generated by Django 5.1.6 on 2025-07-13 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0161_alter_residentactivity_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
