# Generated by Django 5.1.6 on 2025-08-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0162_contract_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewitem',
            name='is_link',
            field=models.BooleanField(default=False, verbose_name='É um link?'),
        ),
    ]
