# Generated by Django 5.1.6 on 2025-10-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0164_alter_bill_created_alter_checklist_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitant',
            name='delivery_code',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
