# Generated by Django 5.1.6 on 2025-10-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0165_visitant_delivery_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(editable=False),
        ),
    ]
