# Generated by Django 5.1.6 on 2025-10-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0166_alter_review_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominiumprofile',
            name='use_tabs',
            field=models.BooleanField(default=False),
        ),
    ]
