# Generated by Django 4.2.1 on 2026-03-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0167_alter_condominiumprofile_use_tabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedestrian',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedestrian',
            name='leaved_in',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='leaved_in',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
