#server {
    #if ($host = www.appportaria.com) {
     #   return 301 https://$host$request_uri;
   # } # managed by Certbot


    #if ($host = appportaria.com) {
     #   return 301 https://$host$request_uri;
    #} # managed by Certbot


    #listen 80;
   # server_name appportaria.com www.appportaria.com;
    #return 301 https://$host$request_uri;




#}

#server {
#    listen 80;
#    server_name appportaria.com.br www.appportaria.com.br;
#    return 301 https://$host$request_uri;
#}

server {
    server_name appportaria.com www.appportaria.com;
    #ssl_certificate /etc/letsencrypt/live/appportaria.com/fullchain.pem; # managed by Certbot
    #ssl_certificate_key /etc/letsencrypt/live/appportaria.com/privkey.pem; # managed by Certbot

    #include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    #ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    client_max_body_size 100M;
    client_body_buffer_size 100M;

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location /static/ {
        alias /var/www/static_cdn/;
    }

    location /media/ {
        alias /var/www/media_cdn/;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;

    }



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/appportaria.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/appportaria.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}

#server {
#    listen 443 ssl;
 #   server_name appportaria.com.br www.appportaria.com.br;
#    ssl_certificate /root/server-br.crt; # managed by Certbot
#    ssl_certificate_key /root/server-br.key; # managed by Certbot

 #   include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
 #   ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

 #   client_max_body_size 100M;
 #   client_body_buffer_size 100M;
#
 #   location = /favicon.ico {
  #      access_log off;
   #     log_not_found off;
    #}

   # location /static/ {
    #    alias /var/www/static_cdn/;
    #}

    #location /media/ {
     #   alias /var/www/media_cdn/;
    #}

    #location / {
    #    include proxy_params;
    #    proxy_pass http://unix:/run/gunicorn.sock;

    #}
#}


server {
    if ($host = www.appportaria.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = appportaria.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name appportaria.com www.appportaria.com;
    return 404; # managed by Certbot




}
